### PR TITLE
Fix an infinite loop in lazy_dots(.follow_symbols = TRUE)

### PR DESCRIPTION
**Pull request by gaborcsardi**

### CODE REVIEW

**Comment by hadley** [comment]
Could you update news please?

**Comment by gaborcsardi** [comment]
The patch does update the NEWS. You mean to rebase?

**Comment by hadley** [comment]
I meant put the bullet in the right place, given the recent cran release

**Comment by gaborcsardi** [comment]
Should be OK now.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
